url: https://ronierisonmaciel.github.io
baseurl: ""

# Site settings
title: Roni Maciel
email: ronierison.maciel@gmail.com
description: "Bem-vindo ao site do Roni Maciel, um entusiasta da tecnologia e inovação. Aqui, você encontrará reflexões sobre as últimas tendências digitais, projetos pessoais e insights sobre a intersecção entre tecnologia e vida cotidiana. Explore, conecte-se e inspire-se com o mundo digital através da minha perspectiva."

# Team names, titles and social links
people:
- name: Ronierison Maciel
  pic: 1
  position: Lead Developer
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/ronierisonmaciel/
    - title: github
      url: https://github.com/RonierisonMaciel
    - title: stack-overflow
      url: https://stackoverflow.com/users/22103002/roni-maciel
    - title: twitter
      url: https://twitter.com/ronimaciell

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
